default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: unit
  password: unit237942
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: octopus_shards1
