octopus:
  verify_connection: true
  replicated: true
  fully_replicated: false

  environments:
    - development
    - production

  development:
    slave1:
      adapter: postgresql
      encoding: unicode
      host: 192.168.0.103
      username: unit
      password: unit237942
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      database: octopus_shards1
  #
  #    slave2:
  #      adapter: postgresql
  #      encoding: unicode
  #      host: 192.168.0.103
  #      username: deploy
  #      password: deploy237942
  #      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #      database: octopus_shards3

#  production:
#      europe_databases:
#        slave1:
#          adapter: postgresql
#          encoding: unicode
#          host: 192.168.0.103
#          username: unit
#          password: unit237942
#          pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#          database: octopus_shards1